/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./src/components/Theme/DarkModeToggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FullScreen: typeof import('./src/components/Theme/FullScreen.vue')['default']
    IconFontIcon: typeof import('./src/components/Icon/IconFontIcon.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
  }
}

// For TSX support
declare global {
  const DarkModeToggle: typeof import('./src/components/Theme/DarkModeToggle.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const FullScreen: typeof import('./src/components/Theme/FullScreen.vue')['default']
  const IconFontIcon: typeof import('./src/components/Icon/IconFontIcon.vue')['default']
  const IconList: typeof import('./src/components/Icon/IconList.vue')['default']
  const IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
  const NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
}