/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Charts: typeof import('./src/components/chart/Charts.vue')['default']
    DarkModeToggle: typeof import('./src/components/Theme/DarkModeToggle.vue')['default']
    Editor: typeof import('./src/components/Editor/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FullScreen: typeof import('./src/components/Theme/FullScreen.vue')['default']
    IconFontIcon: typeof import('./src/components/Icon/IconFontIcon.vue')['default']
    Iconify: typeof import('./src/components/Icon/Iconify.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    Notice: typeof import('./src/components/Notice/Notice.vue')['default']
    NoticeMessageList: typeof import('./src/components/Notice/NoticeMessageList.vue')['default']
    Notification: typeof import('./src/components/Notice/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    VTable: typeof import('./src/components/Table/VTable.vue')['default']
    VTableColumn: typeof import('./src/components/Table/VTableColumn.vue')['default']
    VueEcharts: typeof import('./src/components/chart/VueEcharts.vue')['default']
  }
}

// For TSX support
declare global {
  const Charts: typeof import('./src/components/chart/Charts.vue')['default']
  const DarkModeToggle: typeof import('./src/components/Theme/DarkModeToggle.vue')['default']
  const Editor: typeof import('./src/components/Editor/Editor.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const FullScreen: typeof import('./src/components/Theme/FullScreen.vue')['default']
  const IconFontIcon: typeof import('./src/components/Icon/IconFontIcon.vue')['default']
  const Iconify: typeof import('./src/components/Icon/Iconify.vue')['default']
  const IconList: typeof import('./src/components/Icon/IconList.vue')['default']
  const IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
  const NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
  const Notice: typeof import('./src/components/Notice/Notice.vue')['default']
  const NoticeMessageList: typeof import('./src/components/Notice/NoticeMessageList.vue')['default']
  const Notification: typeof import('./src/components/Notice/Notification.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
  const VTable: typeof import('./src/components/Table/VTable.vue')['default']
  const VTableColumn: typeof import('./src/components/Table/VTableColumn.vue')['default']
  const VueEcharts: typeof import('./src/components/chart/VueEcharts.vue')['default']
}