/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/chart': RouteRecordInfo<
      '/chart',
      '/chart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/directives': RouteRecordInfo<
      '/directives',
      '/directives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ep-icon-list': RouteRecordInfo<
      '/ep-icon-list',
      '/ep-icon-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ep-icon-picker': RouteRecordInfo<
      '/ep-icon-picker',
      '/ep-icon-picker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notice-message': RouteRecordInfo<
      '/notice-message',
      '/notice-message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/table': RouteRecordInfo<
      '/table',
      '/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/table-column-detail': RouteRecordInfo<
      '/table-column-detail',
      '/table-column-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/table-popover': RouteRecordInfo<
      '/table-popover',
      '/table-popover',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/table-select': RouteRecordInfo<
      '/table-select',
      '/table-select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...404].vue': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'src/pages/chart.vue': {
      routes:
        | '/chart'
      views:
        | never
    }
    'src/pages/directives.vue': {
      routes:
        | '/directives'
      views:
        | never
    }
    'src/pages/ep-icon-list.vue': {
      routes:
        | '/ep-icon-list'
      views:
        | never
    }
    'src/pages/ep-icon-picker.vue': {
      routes:
        | '/ep-icon-picker'
      views:
        | never
    }
    'src/pages/notice-message.vue': {
      routes:
        | '/notice-message'
      views:
        | never
    }
    'src/pages/table.vue': {
      routes:
        | '/table'
      views:
        | never
    }
    'src/pages/table-column-detail.vue': {
      routes:
        | '/table-column-detail'
      views:
        | never
    }
    'src/pages/table-popover.vue': {
      routes:
        | '/table-popover'
      views:
        | never
    }
    'src/pages/table-select.vue': {
      routes:
        | '/table-select'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
