name: 'action-demo'

on:
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          version: 11

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: install
        run: pnpm install

      # 如果是自定义的域名，则不需要配置下面的内容
      # - name: Extract repository name
      # 提取仓库名称，用于设置网站前缀
      # run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: build
        env:
          # BASE_PATH: '/${{ env.REPO_NAME }}/'
          BASE_PATH: '/'
        # run: pnpm build
        run: pnpm build:pages

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          # 上传 dist 文件夹
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5


      # - name: display dist list
      #   run: ls -la && ls dist/

      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v5
      #   with:
      #     target_branch: gh-pages
      #     build_dir: dist
      #     jekyll: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
